// <auto-generated />
using System;
using App.DataAccess.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace App.DataAccess.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20231013120935_1002_configurationRefactoringDataSeeded")]
    partial class _1002_configurationRefactoringDataSeeded
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("App.Entities.Concrete.Ability", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Charisma")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<int>("Constitution")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Dexterity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<int>("Intelligence")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<int>("Strength")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Wisdom")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasKey("Id");

                    b.ToTable("Abilites");
                });

            modelBuilder.Entity("App.Entities.Concrete.Character", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AbilityId")
                        .HasColumnType("int");

                    b.Property<int>("CharacterLevel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("RaceId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AbilityId");

                    b.HasIndex("RaceId");

                    b.ToTable("Characters");
                });

            modelBuilder.Entity("App.Entities.Concrete.CharacterClass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CharacterId")
                        .HasColumnType("int");

                    b.Property<int>("ClassId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.HasIndex("ClassId");

                    b.ToTable("CharacterClasses");
                });

            modelBuilder.Entity("App.Entities.Concrete.Class", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Classess");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2023, 10, 13, 15, 9, 35, 700, DateTimeKind.Local).AddTicks(9102),
                            Name = "Barbarian"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2023, 10, 13, 15, 9, 35, 700, DateTimeKind.Local).AddTicks(9108),
                            Name = "Bard"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2023, 10, 13, 15, 9, 35, 700, DateTimeKind.Local).AddTicks(9109),
                            Name = "Cleric"
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2023, 10, 13, 15, 9, 35, 700, DateTimeKind.Local).AddTicks(9110),
                            Name = "Druid"
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2023, 10, 13, 15, 9, 35, 700, DateTimeKind.Local).AddTicks(9111),
                            Name = "Fighter"
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2023, 10, 13, 15, 9, 35, 700, DateTimeKind.Local).AddTicks(9113),
                            Name = "Monk"
                        },
                        new
                        {
                            Id = 7,
                            CreatedDate = new DateTime(2023, 10, 13, 15, 9, 35, 700, DateTimeKind.Local).AddTicks(9113),
                            Name = "Paladin"
                        },
                        new
                        {
                            Id = 8,
                            CreatedDate = new DateTime(2023, 10, 13, 15, 9, 35, 700, DateTimeKind.Local).AddTicks(9114),
                            Name = "Ranger"
                        },
                        new
                        {
                            Id = 9,
                            CreatedDate = new DateTime(2023, 10, 13, 15, 9, 35, 700, DateTimeKind.Local).AddTicks(9115),
                            Name = "Rogue"
                        },
                        new
                        {
                            Id = 10,
                            CreatedDate = new DateTime(2023, 10, 13, 15, 9, 35, 700, DateTimeKind.Local).AddTicks(9116),
                            Name = "Sorcerer"
                        },
                        new
                        {
                            Id = 11,
                            CreatedDate = new DateTime(2023, 10, 13, 15, 9, 35, 700, DateTimeKind.Local).AddTicks(9117),
                            Name = "Warlock"
                        },
                        new
                        {
                            Id = 12,
                            CreatedDate = new DateTime(2023, 10, 13, 15, 9, 35, 700, DateTimeKind.Local).AddTicks(9118),
                            Name = "Wizard"
                        });
                });

            modelBuilder.Entity("App.Entities.Concrete.ClassSubclass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClassId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("SubclassId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.HasIndex("SubclassId");

                    b.ToTable("ClassSubclasses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClassId = 1,
                            CreatedDate = new DateTime(2023, 10, 13, 15, 9, 35, 700, DateTimeKind.Local).AddTicks(7651),
                            SubclassId = 1
                        },
                        new
                        {
                            Id = 2,
                            ClassId = 1,
                            CreatedDate = new DateTime(2023, 10, 13, 15, 9, 35, 700, DateTimeKind.Local).AddTicks(7664),
                            SubclassId = 2
                        },
                        new
                        {
                            Id = 3,
                            ClassId = 1,
                            CreatedDate = new DateTime(2023, 10, 13, 15, 9, 35, 700, DateTimeKind.Local).AddTicks(7665),
                            SubclassId = 3
                        },
                        new
                        {
                            Id = 4,
                            ClassId = 2,
                            CreatedDate = new DateTime(2023, 10, 13, 15, 9, 35, 700, DateTimeKind.Local).AddTicks(7666),
                            SubclassId = 4
                        },
                        new
                        {
                            Id = 5,
                            ClassId = 2,
                            CreatedDate = new DateTime(2023, 10, 13, 15, 9, 35, 700, DateTimeKind.Local).AddTicks(7667),
                            SubclassId = 5
                        },
                        new
                        {
                            Id = 6,
                            ClassId = 2,
                            CreatedDate = new DateTime(2023, 10, 13, 15, 9, 35, 700, DateTimeKind.Local).AddTicks(7669),
                            SubclassId = 6
                        },
                        new
                        {
                            Id = 7,
                            ClassId = 3,
                            CreatedDate = new DateTime(2023, 10, 13, 15, 9, 35, 700, DateTimeKind.Local).AddTicks(7670),
                            SubclassId = 7
                        },
                        new
                        {
                            Id = 8,
                            ClassId = 3,
                            CreatedDate = new DateTime(2023, 10, 13, 15, 9, 35, 700, DateTimeKind.Local).AddTicks(7670),
                            SubclassId = 8
                        },
                        new
                        {
                            Id = 9,
                            ClassId = 3,
                            CreatedDate = new DateTime(2023, 10, 13, 15, 9, 35, 700, DateTimeKind.Local).AddTicks(7671),
                            SubclassId = 9
                        },
                        new
                        {
                            Id = 10,
                            ClassId = 3,
                            CreatedDate = new DateTime(2023, 10, 13, 15, 9, 35, 700, DateTimeKind.Local).AddTicks(7673),
                            SubclassId = 10
                        },
                        new
                        {
                            Id = 11,
                            ClassId = 3,
                            CreatedDate = new DateTime(2023, 10, 13, 15, 9, 35, 700, DateTimeKind.Local).AddTicks(7673),
                            SubclassId = 11
                        },
                        new
                        {
                            Id = 12,
                            ClassId = 3,
                            CreatedDate = new DateTime(2023, 10, 13, 15, 9, 35, 700, DateTimeKind.Local).AddTicks(7674),
                            SubclassId = 12
                        },
                        new
                        {
                            Id = 13,
                            ClassId = 3,
                            CreatedDate = new DateTime(2023, 10, 13, 15, 9, 35, 700, DateTimeKind.Local).AddTicks(7675),
                            SubclassId = 13
                        },
                        new
                        {
                            Id = 14,
                            ClassId = 4,
                            CreatedDate = new DateTime(2023, 10, 13, 15, 9, 35, 700, DateTimeKind.Local).AddTicks(7676),
                            SubclassId = 14
                        },
                        new
                        {
                            Id = 15,
                            ClassId = 4,
                            CreatedDate = new DateTime(2023, 10, 13, 15, 9, 35, 700, DateTimeKind.Local).AddTicks(7676),
                            SubclassId = 15
                        },
                        new
                        {
                            Id = 16,
                            ClassId = 4,
                            CreatedDate = new DateTime(2023, 10, 13, 15, 9, 35, 700, DateTimeKind.Local).AddTicks(7677),
                            SubclassId = 16
                        },
                        new
                        {
                            Id = 17,
                            ClassId = 5,
                            CreatedDate = new DateTime(2023, 10, 13, 15, 9, 35, 700, DateTimeKind.Local).AddTicks(7678),
                            SubclassId = 17
                        },
                        new
                        {
                            Id = 18,
                            ClassId = 5,
                            CreatedDate = new DateTime(2023, 10, 13, 15, 9, 35, 700, DateTimeKind.Local).AddTicks(7679),
                            SubclassId = 18
                        },
                        new
                        {
                            Id = 19,
                            ClassId = 5,
                            CreatedDate = new DateTime(2023, 10, 13, 15, 9, 35, 700, DateTimeKind.Local).AddTicks(7680),
                            SubclassId = 19
                        },
                        new
                        {
                            Id = 20,
                            ClassId = 6,
                            CreatedDate = new DateTime(2023, 10, 13, 15, 9, 35, 700, DateTimeKind.Local).AddTicks(7681),
                            SubclassId = 20
                        },
                        new
                        {
                            Id = 21,
                            ClassId = 6,
                            CreatedDate = new DateTime(2023, 10, 13, 15, 9, 35, 700, DateTimeKind.Local).AddTicks(7682),
                            SubclassId = 21
                        },
                        new
                        {
                            Id = 22,
                            ClassId = 6,
                            CreatedDate = new DateTime(2023, 10, 13, 15, 9, 35, 700, DateTimeKind.Local).AddTicks(7682),
                            SubclassId = 22
                        },
                        new
                        {
                            Id = 23,
                            ClassId = 7,
                            CreatedDate = new DateTime(2023, 10, 13, 15, 9, 35, 700, DateTimeKind.Local).AddTicks(7683),
                            SubclassId = 23
                        },
                        new
                        {
                            Id = 24,
                            ClassId = 7,
                            CreatedDate = new DateTime(2023, 10, 13, 15, 9, 35, 700, DateTimeKind.Local).AddTicks(7684),
                            SubclassId = 24
                        },
                        new
                        {
                            Id = 25,
                            ClassId = 7,
                            CreatedDate = new DateTime(2023, 10, 13, 15, 9, 35, 700, DateTimeKind.Local).AddTicks(7685),
                            SubclassId = 25
                        },
                        new
                        {
                            Id = 26,
                            ClassId = 7,
                            CreatedDate = new DateTime(2023, 10, 13, 15, 9, 35, 700, DateTimeKind.Local).AddTicks(7685),
                            SubclassId = 26
                        },
                        new
                        {
                            Id = 27,
                            ClassId = 8,
                            CreatedDate = new DateTime(2023, 10, 13, 15, 9, 35, 700, DateTimeKind.Local).AddTicks(7686),
                            SubclassId = 27
                        },
                        new
                        {
                            Id = 28,
                            ClassId = 8,
                            CreatedDate = new DateTime(2023, 10, 13, 15, 9, 35, 700, DateTimeKind.Local).AddTicks(7687),
                            SubclassId = 28
                        },
                        new
                        {
                            Id = 29,
                            ClassId = 8,
                            CreatedDate = new DateTime(2023, 10, 13, 15, 9, 35, 700, DateTimeKind.Local).AddTicks(7687),
                            SubclassId = 29
                        },
                        new
                        {
                            Id = 30,
                            ClassId = 9,
                            CreatedDate = new DateTime(2023, 10, 13, 15, 9, 35, 700, DateTimeKind.Local).AddTicks(7688),
                            SubclassId = 30
                        },
                        new
                        {
                            Id = 31,
                            ClassId = 9,
                            CreatedDate = new DateTime(2023, 10, 13, 15, 9, 35, 700, DateTimeKind.Local).AddTicks(7689),
                            SubclassId = 31
                        },
                        new
                        {
                            Id = 32,
                            ClassId = 9,
                            CreatedDate = new DateTime(2023, 10, 13, 15, 9, 35, 700, DateTimeKind.Local).AddTicks(7690),
                            SubclassId = 32
                        },
                        new
                        {
                            Id = 33,
                            ClassId = 10,
                            CreatedDate = new DateTime(2023, 10, 13, 15, 9, 35, 700, DateTimeKind.Local).AddTicks(7691),
                            SubclassId = 33
                        },
                        new
                        {
                            Id = 34,
                            ClassId = 10,
                            CreatedDate = new DateTime(2023, 10, 13, 15, 9, 35, 700, DateTimeKind.Local).AddTicks(7692),
                            SubclassId = 34
                        },
                        new
                        {
                            Id = 35,
                            ClassId = 10,
                            CreatedDate = new DateTime(2023, 10, 13, 15, 9, 35, 700, DateTimeKind.Local).AddTicks(7693),
                            SubclassId = 35
                        },
                        new
                        {
                            Id = 36,
                            ClassId = 11,
                            CreatedDate = new DateTime(2023, 10, 13, 15, 9, 35, 700, DateTimeKind.Local).AddTicks(7693),
                            SubclassId = 36
                        },
                        new
                        {
                            Id = 37,
                            ClassId = 11,
                            CreatedDate = new DateTime(2023, 10, 13, 15, 9, 35, 700, DateTimeKind.Local).AddTicks(7694),
                            SubclassId = 37
                        },
                        new
                        {
                            Id = 38,
                            ClassId = 11,
                            CreatedDate = new DateTime(2023, 10, 13, 15, 9, 35, 700, DateTimeKind.Local).AddTicks(7695),
                            SubclassId = 38
                        },
                        new
                        {
                            Id = 39,
                            ClassId = 12,
                            CreatedDate = new DateTime(2023, 10, 13, 15, 9, 35, 700, DateTimeKind.Local).AddTicks(7696),
                            SubclassId = 39
                        },
                        new
                        {
                            Id = 40,
                            ClassId = 12,
                            CreatedDate = new DateTime(2023, 10, 13, 15, 9, 35, 700, DateTimeKind.Local).AddTicks(7696),
                            SubclassId = 40
                        },
                        new
                        {
                            Id = 41,
                            ClassId = 12,
                            CreatedDate = new DateTime(2023, 10, 13, 15, 9, 35, 700, DateTimeKind.Local).AddTicks(7697),
                            SubclassId = 41
                        },
                        new
                        {
                            Id = 42,
                            ClassId = 12,
                            CreatedDate = new DateTime(2023, 10, 13, 15, 9, 35, 700, DateTimeKind.Local).AddTicks(7698),
                            SubclassId = 42
                        },
                        new
                        {
                            Id = 43,
                            ClassId = 12,
                            CreatedDate = new DateTime(2023, 10, 13, 15, 9, 35, 700, DateTimeKind.Local).AddTicks(7698),
                            SubclassId = 43
                        },
                        new
                        {
                            Id = 44,
                            ClassId = 12,
                            CreatedDate = new DateTime(2023, 10, 13, 15, 9, 35, 700, DateTimeKind.Local).AddTicks(7699),
                            SubclassId = 44
                        },
                        new
                        {
                            Id = 45,
                            ClassId = 12,
                            CreatedDate = new DateTime(2023, 10, 13, 15, 9, 35, 700, DateTimeKind.Local).AddTicks(7700),
                            SubclassId = 45
                        },
                        new
                        {
                            Id = 46,
                            ClassId = 12,
                            CreatedDate = new DateTime(2023, 10, 13, 15, 9, 35, 700, DateTimeKind.Local).AddTicks(7701),
                            SubclassId = 46
                        });
                });

            modelBuilder.Entity("App.Entities.Concrete.Race", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Races");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2023, 10, 13, 15, 9, 35, 701, DateTimeKind.Local).AddTicks(447),
                            Name = "Human"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2023, 10, 13, 15, 9, 35, 701, DateTimeKind.Local).AddTicks(452),
                            Name = "Elf"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2023, 10, 13, 15, 9, 35, 701, DateTimeKind.Local).AddTicks(453),
                            Name = "Drow"
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2023, 10, 13, 15, 9, 35, 701, DateTimeKind.Local).AddTicks(454),
                            Name = "Half-Elf"
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2023, 10, 13, 15, 9, 35, 701, DateTimeKind.Local).AddTicks(455),
                            Name = "Half-Orc"
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2023, 10, 13, 15, 9, 35, 701, DateTimeKind.Local).AddTicks(456),
                            Name = "Halfling"
                        },
                        new
                        {
                            Id = 7,
                            CreatedDate = new DateTime(2023, 10, 13, 15, 9, 35, 701, DateTimeKind.Local).AddTicks(457),
                            Name = "Dwarf"
                        },
                        new
                        {
                            Id = 8,
                            CreatedDate = new DateTime(2023, 10, 13, 15, 9, 35, 701, DateTimeKind.Local).AddTicks(458),
                            Name = "Gnome"
                        },
                        new
                        {
                            Id = 9,
                            CreatedDate = new DateTime(2023, 10, 13, 15, 9, 35, 701, DateTimeKind.Local).AddTicks(458),
                            Name = "Tiefling"
                        },
                        new
                        {
                            Id = 10,
                            CreatedDate = new DateTime(2023, 10, 13, 15, 9, 35, 701, DateTimeKind.Local).AddTicks(460),
                            Name = "Githyanki"
                        },
                        new
                        {
                            Id = 11,
                            CreatedDate = new DateTime(2023, 10, 13, 15, 9, 35, 701, DateTimeKind.Local).AddTicks(461),
                            Name = "Dragonborn"
                        });
                });

            modelBuilder.Entity("App.Entities.Concrete.Subclass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Subclasses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2023, 10, 13, 15, 9, 35, 702, DateTimeKind.Local).AddTicks(343),
                            Name = "Berserker"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2023, 10, 13, 15, 9, 35, 702, DateTimeKind.Local).AddTicks(348),
                            Name = "Wild Magic"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2023, 10, 13, 15, 9, 35, 702, DateTimeKind.Local).AddTicks(349),
                            Name = "Wildheart"
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2023, 10, 13, 15, 9, 35, 702, DateTimeKind.Local).AddTicks(350),
                            Name = "College of Lore"
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2023, 10, 13, 15, 9, 35, 702, DateTimeKind.Local).AddTicks(351),
                            Name = "College of Swords"
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2023, 10, 13, 15, 9, 35, 702, DateTimeKind.Local).AddTicks(353),
                            Name = "College of Valour"
                        },
                        new
                        {
                            Id = 7,
                            CreatedDate = new DateTime(2023, 10, 13, 15, 9, 35, 702, DateTimeKind.Local).AddTicks(354),
                            Name = "Knowledge Domain"
                        },
                        new
                        {
                            Id = 8,
                            CreatedDate = new DateTime(2023, 10, 13, 15, 9, 35, 702, DateTimeKind.Local).AddTicks(355),
                            Name = "Life Domain"
                        },
                        new
                        {
                            Id = 9,
                            CreatedDate = new DateTime(2023, 10, 13, 15, 9, 35, 702, DateTimeKind.Local).AddTicks(355),
                            Name = "Light Domain"
                        },
                        new
                        {
                            Id = 10,
                            CreatedDate = new DateTime(2023, 10, 13, 15, 9, 35, 702, DateTimeKind.Local).AddTicks(356),
                            Name = "Nature Domain"
                        },
                        new
                        {
                            Id = 11,
                            CreatedDate = new DateTime(2023, 10, 13, 15, 9, 35, 702, DateTimeKind.Local).AddTicks(357),
                            Name = "Tempest Domain"
                        },
                        new
                        {
                            Id = 12,
                            CreatedDate = new DateTime(2023, 10, 13, 15, 9, 35, 702, DateTimeKind.Local).AddTicks(358),
                            Name = "Trickery Domain"
                        },
                        new
                        {
                            Id = 13,
                            CreatedDate = new DateTime(2023, 10, 13, 15, 9, 35, 702, DateTimeKind.Local).AddTicks(359),
                            Name = "Trickery War Domain"
                        },
                        new
                        {
                            Id = 14,
                            CreatedDate = new DateTime(2023, 10, 13, 15, 9, 35, 702, DateTimeKind.Local).AddTicks(389),
                            Name = "Circle of the Land"
                        },
                        new
                        {
                            Id = 15,
                            CreatedDate = new DateTime(2023, 10, 13, 15, 9, 35, 702, DateTimeKind.Local).AddTicks(390),
                            Name = "Circle of the Moon"
                        },
                        new
                        {
                            Id = 16,
                            CreatedDate = new DateTime(2023, 10, 13, 15, 9, 35, 702, DateTimeKind.Local).AddTicks(390),
                            Name = "Circle of the Spores"
                        },
                        new
                        {
                            Id = 17,
                            CreatedDate = new DateTime(2023, 10, 13, 15, 9, 35, 702, DateTimeKind.Local).AddTicks(391),
                            Name = "Battle Master"
                        },
                        new
                        {
                            Id = 18,
                            CreatedDate = new DateTime(2023, 10, 13, 15, 9, 35, 702, DateTimeKind.Local).AddTicks(393),
                            Name = "Champion"
                        },
                        new
                        {
                            Id = 19,
                            CreatedDate = new DateTime(2023, 10, 13, 15, 9, 35, 702, DateTimeKind.Local).AddTicks(393),
                            Name = "Eldritch Knight"
                        },
                        new
                        {
                            Id = 20,
                            CreatedDate = new DateTime(2023, 10, 13, 15, 9, 35, 702, DateTimeKind.Local).AddTicks(394),
                            Name = "Way of the Open Hand"
                        },
                        new
                        {
                            Id = 21,
                            CreatedDate = new DateTime(2023, 10, 13, 15, 9, 35, 702, DateTimeKind.Local).AddTicks(395),
                            Name = "Way of Shadow"
                        },
                        new
                        {
                            Id = 22,
                            CreatedDate = new DateTime(2023, 10, 13, 15, 9, 35, 702, DateTimeKind.Local).AddTicks(395),
                            Name = "Way of the Four Elements"
                        },
                        new
                        {
                            Id = 23,
                            CreatedDate = new DateTime(2023, 10, 13, 15, 9, 35, 702, DateTimeKind.Local).AddTicks(396),
                            Name = "Oath of the Ancients"
                        },
                        new
                        {
                            Id = 24,
                            CreatedDate = new DateTime(2023, 10, 13, 15, 9, 35, 702, DateTimeKind.Local).AddTicks(397),
                            Name = "Oath of Devotion"
                        },
                        new
                        {
                            Id = 25,
                            CreatedDate = new DateTime(2023, 10, 13, 15, 9, 35, 702, DateTimeKind.Local).AddTicks(397),
                            Name = "Oath of Vengeance"
                        },
                        new
                        {
                            Id = 26,
                            CreatedDate = new DateTime(2023, 10, 13, 15, 9, 35, 702, DateTimeKind.Local).AddTicks(398),
                            Name = "Oathbreaker"
                        },
                        new
                        {
                            Id = 27,
                            CreatedDate = new DateTime(2023, 10, 13, 15, 9, 35, 702, DateTimeKind.Local).AddTicks(399),
                            Name = "Hunter"
                        },
                        new
                        {
                            Id = 28,
                            CreatedDate = new DateTime(2023, 10, 13, 15, 9, 35, 702, DateTimeKind.Local).AddTicks(399),
                            Name = "Beast Master"
                        },
                        new
                        {
                            Id = 29,
                            CreatedDate = new DateTime(2023, 10, 13, 15, 9, 35, 702, DateTimeKind.Local).AddTicks(400),
                            Name = "Gloom Stalker"
                        },
                        new
                        {
                            Id = 30,
                            CreatedDate = new DateTime(2023, 10, 13, 15, 9, 35, 702, DateTimeKind.Local).AddTicks(401),
                            Name = "Arcane Trickster"
                        },
                        new
                        {
                            Id = 31,
                            CreatedDate = new DateTime(2023, 10, 13, 15, 9, 35, 702, DateTimeKind.Local).AddTicks(401),
                            Name = "Thief"
                        },
                        new
                        {
                            Id = 32,
                            CreatedDate = new DateTime(2023, 10, 13, 15, 9, 35, 702, DateTimeKind.Local).AddTicks(402),
                            Name = "Assassin"
                        },
                        new
                        {
                            Id = 33,
                            CreatedDate = new DateTime(2023, 10, 13, 15, 9, 35, 702, DateTimeKind.Local).AddTicks(403),
                            Name = "Draconic Bloodline"
                        },
                        new
                        {
                            Id = 34,
                            CreatedDate = new DateTime(2023, 10, 13, 15, 9, 35, 702, DateTimeKind.Local).AddTicks(404),
                            Name = "Wild Magic"
                        },
                        new
                        {
                            Id = 35,
                            CreatedDate = new DateTime(2023, 10, 13, 15, 9, 35, 702, DateTimeKind.Local).AddTicks(405),
                            Name = "Storm Sorcery"
                        },
                        new
                        {
                            Id = 36,
                            CreatedDate = new DateTime(2023, 10, 13, 15, 9, 35, 702, DateTimeKind.Local).AddTicks(406),
                            Name = "The Archfey"
                        },
                        new
                        {
                            Id = 37,
                            CreatedDate = new DateTime(2023, 10, 13, 15, 9, 35, 702, DateTimeKind.Local).AddTicks(406),
                            Name = "The Fiend"
                        },
                        new
                        {
                            Id = 38,
                            CreatedDate = new DateTime(2023, 10, 13, 15, 9, 35, 702, DateTimeKind.Local).AddTicks(407),
                            Name = "The Great Old One"
                        },
                        new
                        {
                            Id = 39,
                            CreatedDate = new DateTime(2023, 10, 13, 15, 9, 35, 702, DateTimeKind.Local).AddTicks(407),
                            Name = "Abjuration School"
                        },
                        new
                        {
                            Id = 40,
                            CreatedDate = new DateTime(2023, 10, 13, 15, 9, 35, 702, DateTimeKind.Local).AddTicks(408),
                            Name = "Conjuration School"
                        },
                        new
                        {
                            Id = 41,
                            CreatedDate = new DateTime(2023, 10, 13, 15, 9, 35, 702, DateTimeKind.Local).AddTicks(409),
                            Name = "Divination School"
                        },
                        new
                        {
                            Id = 42,
                            CreatedDate = new DateTime(2023, 10, 13, 15, 9, 35, 702, DateTimeKind.Local).AddTicks(409),
                            Name = "Enchantment School"
                        },
                        new
                        {
                            Id = 43,
                            CreatedDate = new DateTime(2023, 10, 13, 15, 9, 35, 702, DateTimeKind.Local).AddTicks(410),
                            Name = "Evocation School"
                        },
                        new
                        {
                            Id = 44,
                            CreatedDate = new DateTime(2023, 10, 13, 15, 9, 35, 702, DateTimeKind.Local).AddTicks(411),
                            Name = "Illusion School"
                        },
                        new
                        {
                            Id = 45,
                            CreatedDate = new DateTime(2023, 10, 13, 15, 9, 35, 702, DateTimeKind.Local).AddTicks(411),
                            Name = "Necromancy School"
                        },
                        new
                        {
                            Id = 46,
                            CreatedDate = new DateTime(2023, 10, 13, 15, 9, 35, 702, DateTimeKind.Local).AddTicks(412),
                            Name = "Transmutation School"
                        });
                });

            modelBuilder.Entity("App.Entities.Concrete.Character", b =>
                {
                    b.HasOne("App.Entities.Concrete.Ability", "Ability")
                        .WithMany()
                        .HasForeignKey("AbilityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("App.Entities.Concrete.Race", "Race")
                        .WithMany()
                        .HasForeignKey("RaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ability");

                    b.Navigation("Race");
                });

            modelBuilder.Entity("App.Entities.Concrete.CharacterClass", b =>
                {
                    b.HasOne("App.Entities.Concrete.Character", "Character")
                        .WithMany("CharacterClasses")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("App.Entities.Concrete.Class", "Class")
                        .WithMany("CharacterClasses")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");

                    b.Navigation("Class");
                });

            modelBuilder.Entity("App.Entities.Concrete.ClassSubclass", b =>
                {
                    b.HasOne("App.Entities.Concrete.Class", "Class")
                        .WithMany("ClassSubclasses")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("App.Entities.Concrete.Subclass", "Subclass")
                        .WithMany("ClassSubclasses")
                        .HasForeignKey("SubclassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("Subclass");
                });

            modelBuilder.Entity("App.Entities.Concrete.Character", b =>
                {
                    b.Navigation("CharacterClasses");
                });

            modelBuilder.Entity("App.Entities.Concrete.Class", b =>
                {
                    b.Navigation("CharacterClasses");

                    b.Navigation("ClassSubclasses");
                });

            modelBuilder.Entity("App.Entities.Concrete.Subclass", b =>
                {
                    b.Navigation("ClassSubclasses");
                });
#pragma warning restore 612, 618
        }
    }
}
